### ISSUE TITLE
Add support for service to stay in channel

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/pingdom-irc-healthcheck#2]
Currently, the service connects to IRC whenever a check is made, and leaves immediately afterwards. This causes a lot of "x has joined, x has left" messages in the channel.

It would be better if the service maintained an IRC connection, using it as necessary, and re-connecting if it is disconnected.

**Comment by zeisss** [comment]
Actually, why do we need a separate service at all? IRC performs regular pings to a client and the client can do the same thing to a server. Let the HTTP Check from pingdom just do a PING on the irc connection and if that times out, we are down.

**Comment by JosephSalisbury** [comment]
Old. Closing. Bye!
